generate-booking-rpc:
	protoc --go_out=. \
           --go-grpc_out=. \
           --proto_path=. \
           booking_proto/booking.proto

generate-hotels-rpc:
	protoc --go_out=. \
           --go-grpc_out=. \
           --proto_path=. \
           hotels_proto/hotel.proto
