users-generate-rpc:
	protoc --go_out=. \
           --go-grpc_out=. \
           --proto_path=. \
           protos/users_proto/users.proto

hotels-generate-rpc:
	protoc --go_out=. \
           --go-grpc_out=. \
           --proto_path=. \
           protos/hotels_proto/hotel.proto
